### ISSUE TITLE
Not published on NPM

### ISSUE THREAD

**Issue by Explosion-Scratch** [proposal-signals/proposal-signals#82]
`signal-polyfill` wasn't published on NPM so I couldn't use it 😭

I built and published it— Would be happy to transfer the package or whatever to whoever is in charge of this project

**Comment by EisenbergEffect** [comment]
@littledan How should we handle this? What is the precedent with other TC39 proposals and polyfills?

**Comment by littledan** [comment]
Publishing on npm seems like a good idea, as long as we have the appropriate disclaimers about it being in flux, version it 0.x, don’t install it on the global object, etc.

**Comment by EisenbergEffect** [comment]
@Explosion-Scratch If you want to transfer it to EisenbergEffect on NPM, I can take over managing it.

**Comment by NullVoxPopuli** [comment]
once it's published, I can make a pre-1.0 utility library with reactive utilities:

Object, Array, Map, Set, WeakMap, WeakSet, _deep_, localCopy, and probably a few others

**Comment by EisenbergEffect** [comment]
@NullVoxPopuli That would be awesome.

**Comment by Explosion-Scratch** [comment]
@EisenbergEffect You've been invited, once you accept I'll remove myself as a maintainer

**Comment by Explosion-Scratch** [comment]
> once it's published, I can make a pre-1.0 utility library with reactive utilities:
> 
> Object, Array, Map, Set, WeakMap, WeakSet, _deep_, localCopy, and probably a few others

Maybe add in effect to there, it'd be nice to have a simple implementation, then users could build their own implementation of `effect` if they wanted to.

**Comment by EisenbergEffect** [comment]
@Explosion-Scratch The trick with effects is that, at least based on our discussions so far, they tend to be very tightly coupled with the view layer's implementation. So, while a sort of general purpose effect can be written (like in the readme), it's not likely to be something that's useful if you are using some sort of view layer, because you want those two things to be integrated. On the other hand, the reactive collections are pure data structures. So, they can be leveraged in any codebase that integrates with signals. We did start out by trying to have an effect as part of the API, but ran into the above issues, so removed it as it wouldn't be useful for any of the library authors. Let me know if that makes sense.

**Comment by EisenbergEffect** [comment]
Ok. Ownership is transferred to me now. @Explosion-Scratch I've gone ahead and remove you. Thanks for helping out!
